// <auto-generated />
using System;
using DBAplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBAplication.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBAplication.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KeyAuthorized");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DBAplication.Model.Driver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsWork");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Token");

                    b.Property<string>("TokenShope");

                    b.Property<string>("ZipCod");

                    b.Property<int?>("geolocationsID");

                    b.HasKey("ID");

                    b.HasIndex("geolocationsID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DBAplication.Model.Geolocations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.HasKey("ID");

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("DBAplication.Model.OnePointForAddressOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Date");

                    b.Property<int>("IDorder");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<int?>("OrderMobileID");

                    b.Property<string>("PTime");

                    b.Property<string>("Status");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("OrderMobileID");

                    b.ToTable("OnePointForAddressOrder");
                });

            modelBuilder.Entity("DBAplication.Model.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("CountCustomer");

                    b.Property<string>("CurrentOrder");

                    b.Property<string>("CurrentStatus");

                    b.Property<string>("Date");

                    b.Property<int?>("DriverID");

                    b.Property<string>("FB");

                    b.Property<string>("FromAddress");

                    b.Property<int>("FromZip");

                    b.Property<bool>("IsVisableAccept");

                    b.Property<string>("Milisse");

                    b.Property<string>("NameCustomer");

                    b.Property<string>("NoName");

                    b.Property<string>("NoName1");

                    b.Property<string>("NoName2");

                    b.Property<string>("NoName3");

                    b.Property<string>("NoName4");

                    b.Property<string>("NoName5");

                    b.Property<string>("NoName6");

                    b.Property<int?>("OrderMobileID");

                    b.Property<string>("Phone");

                    b.Property<string>("Price");

                    b.Property<string>("TimeOfAppointment");

                    b.Property<string>("TimeOfPickup");

                    b.Property<string>("ToAddress");

                    b.Property<int>("ToZip");

                    b.Property<bool>("isAccept");

                    b.Property<bool>("isValid");

                    b.HasKey("ID");

                    b.HasIndex("DriverID");

                    b.HasIndex("OrderMobileID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DBAplication.Model.OrderMobile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdDriver");

                    b.Property<string>("Status");

                    b.Property<string>("StatusDrive");

                    b.HasKey("ID");

                    b.ToTable("OrderMobiles");
                });

            modelBuilder.Entity("DBAplication.Model.Driver", b =>
                {
                    b.HasOne("DBAplication.Model.Geolocations", "geolocations")
                        .WithMany()
                        .HasForeignKey("geolocationsID");
                });

            modelBuilder.Entity("DBAplication.Model.OnePointForAddressOrder", b =>
                {
                    b.HasOne("DBAplication.Model.OrderMobile")
                        .WithMany("OnePointForAddressOrders")
                        .HasForeignKey("OrderMobileID");
                });

            modelBuilder.Entity("DBAplication.Model.Order", b =>
                {
                    b.HasOne("DBAplication.Model.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.HasOne("DBAplication.Model.OrderMobile")
                        .WithMany("Orders")
                        .HasForeignKey("OrderMobileID");
                });
#pragma warning restore 612, 618
        }
    }
}
